[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "drivers"
version = "0.0"
authors = ["Camera Culture <a2cc@media.mit.edu>"]
description = "CC Hardware Drivers"
readme = "README.md"
packages = [
  { include = "cc_hardware" }
]

[tool.poetry.dependencies]
python = ">=3.12"
numpy = "^2.1.1"
utils = {path = "../utils", develop = true}
