[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "cnc_robot"
version = "0.0"
authors = ["Camera Culture <a2cc@media.mit.edu>"]
description = "CNC Robot"
readme = "README.md"
packages = [
  { include = "cc_hardware" }
]

[tool.poetry.dependencies]
python = ">=3.12"
telemetrix = "1.40"
numpy = "^2.1.1"
tools = {path = "../tools", develop = true}

[tool.poetry.scripts]
jogger = "cc_hardware.cnc_robot.jogger:main"

[tool.poetry-monorepo.deps]
