[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "tools"
version = "0.0"
authors = ["Camera Culture <a2cc@media.mit.edu>"]
description = "CC Hardware Tools"
readme = "README.md"
packages = [
  { include = "cc_hardware" }
]

[tool.poetry.dependencies]
python = ">=3.12"
typer = "^0.12.5"
torch = "^2.4.1"
utils = {path = "../utils", develop = true}
drivers = {path = "../drivers", develop = true}

[tool.poetry.scripts]
cc = "cc_hardware.tools.main:cc"
